services:
  accounts:
    image: mohammedashfaqhussain510/accounts:s4
    container_name: account-ms
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

  loans:
    image: mohammedashfaqhussain510/loans:s4
    container_name: loans-ms
    ports:
      - "8080:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

  cards:
    image: mohammedashfaqhussain510/cards:s4
    container_name: cards-ms
    ports:
      - "8082:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

networks:
  eazybank:
    driver: "bridge"
